apiVersion: v1
kind: Pod
metadata:
  name: triage
spec:
  containers:
  - name: triage
    image: taybart/tools:1.0.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
