apiVersion: v1
kind: Pod
metadata:
  name: triage
  namespace: default
spec:
  containers:
  - name: triage
    image: taybart/tools
    command:
      - sleep
      - "3600"
    imagePullPolicy: Always
  restartPolicy: Always
